# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b7551769aef370e5a78d20c9248d1235ef2a845f9fe526836774752cff28da9da71c293cc3029b00fd17946b913b87170b9db9ee735104a3c323abb4837f456

test:
  secret_key_base: 1a34a9b4287fe42a15c6c92689c92b65954248a8ca2f4737b080bf5b2824c2c1e274c456845faf95c4953bb48ee70f3342a36455b83c5fdd0d496440facebce6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
